// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import "vue"

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    ElButton: typeof import("element-plus/es")["ElButton"]
    ElDatePicker: typeof import("element-plus/es")["ElDatePicker"]
    RouterLink: typeof import("vue-router")["RouterLink"]
    RouterView: typeof import("vue-router")["RouterView"]
    SvgIcon: typeof import("./src/components/common/SvgIcon.vue")["default"]
    TestCom: typeof import("./src/components/common/TestCom.vue")["default"]
  }
}

export {}
